QUESTIONS = [
    {"key": "GENERO", "question": "¿Cuál es tu género?", "answer": None},
    {"key": "NOMBRE", "question": "¿Cómo te llamas?", "answer": None},
    {"key": "EDAD", "question": "¿Cuántos años tienes?", "answer": None},
    {"key": "ESCUELA", "question": "¿Cuál es el nombre de tu escuela?", "answer": None},
    {"key": "GRADO", "question": "¿En qué grado estás?", "answer": None},
    {"key": "GRUPO", "question": "¿En qué grupo estás?", "answer": None},
    {"key": "EF-1", "question": "¿Con quién vives?", "options": ['Mamá', 'Madrastra', 'Hermanas', 'Mascotas', 'Papá', 'Padrastro', 'Hermanos'], "other": True, "answer": None},
    {"key": "RA-2", "question": "¿Quién te cuida?", "answer": None},
    {"key": "RA-3", "question": "¿A quién le platicas cuando sientes felicidad, tristeza, enojo o miedo?", "options": ['Familia', 'Amistades'], "other": True, "answer": None},
    {"key": "RA-4", "question": "¿Tienes amigos o amigas?", "options": ['Sí', 'No'], "answer": None},
    {"key": "A-5", "question": "¿Quién te quiere mucho?", "answer": None},
    {"key": "A-6", "question": "¿Cómo te demuestra que te quiere la persona que te cuida?", "answer": None},
    {"key": "A-7", "question": "¿Tú, a quién quieres mucho?", "answer": None},
    {"key": "A-8", "question": "¿Cómo le demuestras a esa persona que la quieres?", "answer": None},
    {"key": "E-9", "question": "¿Qué haces cuando te sientes triste?", "answer": None},
    {"key": "E-10", "question": "¿Qué haces cuando te sientes enojado o enojada?", "answer": None},
    {"key": "E-11", "question": "¿Qué haces cuando sientes miedo?", "answer": None},
    {"key": "E-12", "question": "¿Qué haces cuando te sientes preocupado o preocupada?", "answer": None},
    {"key": "E-13", "question": "¿Qué haces cuando te sientes feliz?", "answer": None},
    {"key": "FRP-14", "question": "¿Te gusta dormir?", "options": ['Sí', 'No', 'Sí me gusta pero no puedo dormir'], "answer": None},
    {"key": "ERP-14-A", "question": "¿Por qué?", "answer": None},
    {"key": "FRP-15", "question": "¿Te gusta ir a la escuela?", "options": ['Sí', 'No'], "answer": None},
    {"key": "FRP-15-A", "question": "¿Por qué?", "answer": None},
    {"key": "CMU-16", "question": "¿Quiénes pueden morir?", "answer": None},
    {"key": "CMI-17", "question": "¿Después de que alguien muere, puede revivir?", "options": ['Sí', 'No'], "answer": None},
    {"key": "CMSFV-18", "question": "Después de que muere una persona o un animal, ¿el cuerpo deja de funcionar?", "options": ['Sí', 'No'], "answer": None},
    {"key": "CM-16", "question": "¿Qué pasa cuando una persona muere?", "answer": None},
    {"key": "CMCF-20", "question": "¿Por qué puede morir una persona o animal?", "answer": None},
    {"key": "FRP-21", "question": "¿Alguna vez has sentido que quieres dormir y no despertar nunca?", "options": ['Sí', 'No'], "answer": None},
    {"key": "FRP-21-A", "question": "¿Cuándo?", "answer": None},
    {"key": "FRP-22", "question": "¿Alguna vez has sentido que tienes muchas ganas de llorar?", "options": ['Sí', 'No'], "answer": None},
    {"key": "FRP-22-A", "question": "¿Cuándo?", "answer": None},
    {"key": "E-23", "question": "¿Es bueno llorar?", "options": ['Sí', 'No'], "answer": None},
    {"key": "E-23-A", "question": "¿Por qué?", "answer": None},
    {"key": "FRP-24", "question": "¿Alguna vez has sentido que te quieres hacer daño?", "options": ['Sí', 'No'], "answer": None},
    {"key": "FRP-24-A", "question": "¿Cuándo?", "answer": None},
    {"key": "FRP-25", "question": "¿Alguna vez has probado bebidas alcohólicas?", "options": ['Sí', 'No'], "answer": None},
    {"key": "FRP-25-A", "question": "¿Cuándo?", "answer": None},
    {"key": "FRP-26", "question": "¿Alguna vez has fumado?", "options": ['Sí', 'No'], "answer": None},
    {"key": "FRP-26-A", "question": "¿Por qué?", "answer": None},
    {"key": "FRP-27", "question": "¿Te gusta la ropa que usas?", "options": ['Sí', 'No'], "answer": None},
    {"key": "FRP-27-A", "question": "¿Por qué?", "answer": None},
    {"key": "FRP-28", "question": "¿En qué te gustaría trabajar cuando seas grande?", "answer": None},
    {"key": "FRP-29", "question": "¿Qué es lo que más te hace reír?", "answer": None},
]