# Generated by Django 5.1.6 on 2025-02-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
